// <auto-generated />
using System;
using Entities.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Entities.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20220408091133_add isband to joincontest")]
    partial class addisbandtojoincontest
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:Collation", "SQL_Latin1_General_CP1_CI_AS")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.13")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Entities.Models.Account", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Avatar")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<string>("Biography")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<string>("Gender")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<string>("Phone")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<int?>("Role")
                        .HasColumnType("int");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<string>("Uid")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Account");
                });

            modelBuilder.Entity("Entities.Models.Bill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BuyerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<double?>("ExchangeValue")
                        .HasColumnType("float");

                    b.Property<bool>("IsExchangeByMoney")
                        .HasColumnType("bit");

                    b.Property<int>("SellerId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("ToyOfBuyerName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ToyOfSellerName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TradingPostId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BuyerId");

                    b.HasIndex("SellerId");

                    b.HasIndex("TradingPostId");

                    b.ToTable("Bill");
                });

            modelBuilder.Entity("Entities.Models.Brand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Brand");
                });

            modelBuilder.Entity("Entities.Models.Chat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AccountId")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("RoomName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("SendDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.ToTable("Chat");
                });

            modelBuilder.Entity("Entities.Models.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AccountId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CommentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PostId")
                        .HasColumnType("int");

                    b.Property<int?>("TradingPostId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("PostId");

                    b.HasIndex("TradingPostId");

                    b.ToTable("Comment");
                });

            modelBuilder.Entity("Entities.Models.Contest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("BrandId")
                        .HasColumnType("int");

                    b.Property<string>("CoverImage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("EndRegistration")
                        .HasColumnType("datetime");

                    b.Property<int?>("GroupId")
                        .HasColumnType("int");

                    b.Property<int?>("MaxRegistration")
                        .HasColumnType("int");

                    b.Property<int?>("MinRegistration")
                        .HasColumnType("int");

                    b.Property<string>("Rule")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Slogan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("StartRegistration")
                        .HasColumnType("datetime");

                    b.Property<int?>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BrandId");

                    b.HasIndex("TypeId");

                    b.ToTable("Contest");
                });

            modelBuilder.Entity("Entities.Models.ErrorLogs", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ErrorCode")
                        .HasColumnType("int");

                    b.Property<string>("Message")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Error");
                });

            modelBuilder.Entity("Entities.Models.Evaluate", b =>
                {
                    b.Property<int>("ContestId")
                        .HasColumnType("int");

                    b.Property<int>("AccountId")
                        .HasColumnType("int");

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("NoOfStart")
                        .HasColumnType("int");

                    b.HasKey("ContestId", "AccountId");

                    b.HasIndex("AccountId");

                    b.ToTable("Evaluate");
                });

            modelBuilder.Entity("Entities.Models.FavoriteBrand", b =>
                {
                    b.Property<int>("AccountId")
                        .HasColumnType("int");

                    b.Property<int>("BrandId")
                        .HasColumnType("int");

                    b.HasKey("AccountId", "BrandId");

                    b.HasIndex("BrandId");

                    b.ToTable("FavoriteBrand");
                });

            modelBuilder.Entity("Entities.Models.FavoriteType", b =>
                {
                    b.Property<int>("AccountId")
                        .HasColumnType("int");

                    b.Property<int>("TypeId")
                        .HasColumnType("int");

                    b.HasKey("AccountId", "TypeId");

                    b.HasIndex("TypeId");

                    b.ToTable("FavoriteType");
                });

            modelBuilder.Entity("Entities.Models.Feedback", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AccountId")
                        .HasColumnType("int");

                    b.Property<int?>("AccountReplyId")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PostId")
                        .HasColumnType("int");

                    b.Property<int?>("PostOfContestId")
                        .HasColumnType("int");

                    b.Property<string>("ReplyContent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ReplyDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("SendDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("SenderId")
                        .HasColumnType("int");

                    b.Property<int?>("TradingPostId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("AccountReplyId");

                    b.HasIndex("PostId");

                    b.HasIndex("PostOfContestId");

                    b.HasIndex("SenderId");

                    b.HasIndex("TradingPostId");

                    b.ToTable("Feedback");
                });

            modelBuilder.Entity("Entities.Models.FollowAccount", b =>
                {
                    b.Property<int>("AccountId")
                        .HasColumnType("int");

                    b.Property<int>("AccountFollowId")
                        .HasColumnType("int");

                    b.HasKey("AccountId", "AccountFollowId");

                    b.HasIndex("AccountFollowId");

                    b.ToTable("FollowAccount");
                });

            modelBuilder.Entity("Entities.Models.FollowGroup", b =>
                {
                    b.Property<int>("AccountId")
                        .HasColumnType("int");

                    b.Property<int>("GroupId")
                        .HasColumnType("int");

                    b.HasKey("AccountId", "GroupId");

                    b.HasIndex("GroupId");

                    b.ToTable("FollowGroup");
                });

            modelBuilder.Entity("Entities.Models.Group", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDisable")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Group");
                });

            modelBuilder.Entity("Entities.Models.Image", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("BillId")
                        .HasColumnType("int");

                    b.Property<int?>("PostId")
                        .HasColumnType("int");

                    b.Property<int?>("PostOfContestId")
                        .HasColumnType("int");

                    b.Property<int?>("PrizeId")
                        .HasColumnType("int");

                    b.Property<int?>("ToyId")
                        .HasColumnType("int");

                    b.Property<int?>("TradingPostId")
                        .HasColumnType("int");

                    b.Property<string>("Url")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BillId");

                    b.HasIndex("PostId");

                    b.HasIndex("PostOfContestId");

                    b.HasIndex("PrizeId");

                    b.HasIndex("ToyId");

                    b.HasIndex("TradingPostId");

                    b.ToTable("Image");
                });

            modelBuilder.Entity("Entities.Models.JoinedToContest", b =>
                {
                    b.Property<int>("AccountId")
                        .HasColumnType("int");

                    b.Property<int>("ContestId")
                        .HasColumnType("int");

                    b.Property<bool>("IsBan")
                        .HasColumnType("bit");

                    b.HasKey("AccountId", "ContestId");

                    b.HasIndex("ContestId");

                    b.ToTable("JoinedToContest");
                });

            modelBuilder.Entity("Entities.Models.ManageGroup", b =>
                {
                    b.Property<int>("AccountId")
                        .HasColumnType("int");

                    b.Property<int>("GroupId")
                        .HasColumnType("int");

                    b.HasKey("AccountId", "GroupId");

                    b.HasIndex("GroupId");

                    b.ToTable("ManageGroup");
                });

            modelBuilder.Entity("Entities.Models.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AccountId")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ContestId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsReaded")
                        .HasColumnType("bit");

                    b.Property<int?>("PostId")
                        .HasColumnType("int");

                    b.Property<int?>("PostOfContestId")
                        .HasColumnType("int");

                    b.Property<int?>("TradingPostId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("ContestId");

                    b.HasIndex("PostId");

                    b.HasIndex("PostOfContestId");

                    b.HasIndex("TradingPostId");

                    b.ToTable("Notification");
                });

            modelBuilder.Entity("Entities.Models.Post", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AccountId")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("GroupId")
                        .HasColumnType("int");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsPublic")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsWaiting")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("PostDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("PublicDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ToyId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("GroupId");

                    b.HasIndex("ToyId");

                    b.ToTable("Post");
                });

            modelBuilder.Entity("Entities.Models.PostOfContest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AccountId")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ContestId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DateCreate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("ContestId");

                    b.ToTable("PostOfContest");
                });

            modelBuilder.Entity("Entities.Models.Prize", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDisabled")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Prize");
                });

            modelBuilder.Entity("Entities.Models.PrizeContest", b =>
                {
                    b.Property<int>("ContestId")
                        .HasColumnType("int");

                    b.Property<int>("PrizeId")
                        .HasColumnType("int");

                    b.HasKey("ContestId", "PrizeId");

                    b.HasIndex("PrizeId");

                    b.ToTable("Prize_Contest");
                });

            modelBuilder.Entity("Entities.Models.Rate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AccountId")
                        .HasColumnType("int");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumOfStar")
                        .HasColumnType("int");

                    b.Property<int>("PostOfContestId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("PostOfContestId");

                    b.ToTable("Rate");
                });

            modelBuilder.Entity("Entities.Models.RateSeller", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BuyerId")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumOfStar")
                        .HasColumnType("int");

                    b.Property<int>("SellerId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BuyerId");

                    b.HasIndex("SellerId");

                    b.ToTable("RateSeller");
                });

            modelBuilder.Entity("Entities.Models.ReactComment", b =>
                {
                    b.Property<int>("AccountId")
                        .HasColumnType("int");

                    b.Property<int>("CommentId")
                        .HasColumnType("int");

                    b.HasKey("AccountId", "CommentId");

                    b.HasIndex("CommentId");

                    b.ToTable("ReactComment");
                });

            modelBuilder.Entity("Entities.Models.ReactPost", b =>
                {
                    b.Property<int>("AccountId")
                        .HasColumnType("int");

                    b.Property<int>("PostId")
                        .HasColumnType("int");

                    b.HasKey("AccountId", "PostId");

                    b.HasIndex("PostId");

                    b.ToTable("ReactPost");
                });

            modelBuilder.Entity("Entities.Models.ReactTradingPost", b =>
                {
                    b.Property<int>("AccountId")
                        .HasColumnType("int");

                    b.Property<int>("TradingPostId")
                        .HasColumnType("int");

                    b.HasKey("AccountId", "TradingPostId");

                    b.HasIndex("TradingPostId");

                    b.ToTable("ReactTradingPost");
                });

            modelBuilder.Entity("Entities.Models.Reward", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AccountId")
                        .HasColumnType("int");

                    b.Property<int>("ContestId")
                        .HasColumnType("int");

                    b.Property<int>("PostOfContestId")
                        .HasColumnType("int");

                    b.Property<int>("PrizeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("ContestId");

                    b.HasIndex("PostOfContestId");

                    b.HasIndex("PrizeId");

                    b.ToTable("Reward");
                });

            modelBuilder.Entity("Entities.Models.Toy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("BrandId")
                        .HasColumnType("int");

                    b.Property<string>("CoverImage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(11,2)");

                    b.Property<int?>("TypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BrandId");

                    b.HasIndex("TypeId");

                    b.ToTable("Toy");
                });

            modelBuilder.Entity("Entities.Models.TradingPost", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AccountId")
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("BrandId")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GroupId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsExchanged")
                        .HasColumnType("bit");

                    b.Property<string>("Phone")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<DateTime>("PostDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ToyId")
                        .HasColumnType("int");

                    b.Property<string>("ToyName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Trading")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TypeId")
                        .HasColumnType("int");

                    b.Property<decimal?>("Value")
                        .HasColumnType("decimal(9,2)");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("BrandId");

                    b.HasIndex("GroupId");

                    b.HasIndex("ToyId");

                    b.HasIndex("TypeId");

                    b.ToTable("TradingPost");
                });

            modelBuilder.Entity("Entities.Models.Type", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Type");
                });

            modelBuilder.Entity("Entities.Models.Bill", b =>
                {
                    b.HasOne("Entities.Models.Account", "Buyer")
                        .WithMany("BillsBuyer")
                        .HasForeignKey("BuyerId")
                        .HasConstraintName("FK_Bill_Account_Buyer")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entities.Models.Account", "Seller")
                        .WithMany("BillsSeler")
                        .HasForeignKey("SellerId")
                        .HasConstraintName("FK_Bill_Account_Seller")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entities.Models.TradingPost", "TradingPost")
                        .WithMany("Bills")
                        .HasForeignKey("TradingPostId")
                        .HasConstraintName("FK_Bill_TradingPost")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Buyer");

                    b.Navigation("Seller");

                    b.Navigation("TradingPost");
                });

            modelBuilder.Entity("Entities.Models.Chat", b =>
                {
                    b.HasOne("Entities.Models.Account", "Account")
                        .WithMany("Chats")
                        .HasForeignKey("AccountId")
                        .HasConstraintName("FK_Chat_Account_AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("Entities.Models.Comment", b =>
                {
                    b.HasOne("Entities.Models.Account", "Account")
                        .WithMany("Comments")
                        .HasForeignKey("AccountId")
                        .HasConstraintName("FK_Comment_Account");

                    b.HasOne("Entities.Models.Post", "Post")
                        .WithMany("Comments")
                        .HasForeignKey("PostId")
                        .HasConstraintName("FK_Comment_Post");

                    b.HasOne("Entities.Models.TradingPost", "TradingPost")
                        .WithMany("Comments")
                        .HasForeignKey("TradingPostId");

                    b.Navigation("Account");

                    b.Navigation("Post");

                    b.Navigation("TradingPost");
                });

            modelBuilder.Entity("Entities.Models.Contest", b =>
                {
                    b.HasOne("Entities.Models.Brand", "Brand")
                        .WithMany("Contests")
                        .HasForeignKey("BrandId")
                        .HasConstraintName("FK_Contest_Brand");

                    b.HasOne("Entities.Models.Type", "Type")
                        .WithMany("Contests")
                        .HasForeignKey("TypeId")
                        .HasConstraintName("FK_Contest_Type");

                    b.Navigation("Brand");

                    b.Navigation("Type");
                });

            modelBuilder.Entity("Entities.Models.Evaluate", b =>
                {
                    b.HasOne("Entities.Models.Account", "Account")
                        .WithMany("Evaluates")
                        .HasForeignKey("AccountId")
                        .HasConstraintName("FK_Evaluate_Account")
                        .IsRequired();

                    b.HasOne("Entities.Models.Contest", "Contest")
                        .WithMany("Evaluates")
                        .HasForeignKey("ContestId")
                        .HasConstraintName("FK_Evaluate_Contest")
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("Contest");
                });

            modelBuilder.Entity("Entities.Models.FavoriteBrand", b =>
                {
                    b.HasOne("Entities.Models.Account", "Account")
                        .WithMany("FavoriteBrands")
                        .HasForeignKey("AccountId")
                        .HasConstraintName("FK_Brand_Account_FavoriteBrandAccount")
                        .IsRequired();

                    b.HasOne("Entities.Models.Brand", "Brand")
                        .WithMany("FavoriteBrands")
                        .HasForeignKey("BrandId")
                        .HasConstraintName("FK_Type_Account_FavoriteBrandBrand")
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("Brand");
                });

            modelBuilder.Entity("Entities.Models.FavoriteType", b =>
                {
                    b.HasOne("Entities.Models.Account", "Account")
                        .WithMany("FavoriteTypes")
                        .HasForeignKey("AccountId")
                        .HasConstraintName("FK_Type_Account_FavoriteTypeAccount")
                        .IsRequired();

                    b.HasOne("Entities.Models.Type", "Type")
                        .WithMany("FavoriteTypes")
                        .HasForeignKey("TypeId")
                        .HasConstraintName("FK_Type_Account_FavoriteTypeType")
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("Type");
                });

            modelBuilder.Entity("Entities.Models.Feedback", b =>
                {
                    b.HasOne("Entities.Models.Account", "Account")
                        .WithMany("FeedbackAccounts")
                        .HasForeignKey("AccountId")
                        .HasConstraintName("FK_Feedback_Account");

                    b.HasOne("Entities.Models.Account", "AccountReply")
                        .WithMany("FeedbackAccountReplies")
                        .HasForeignKey("AccountReplyId")
                        .HasConstraintName("FK_Feedback_Account2");

                    b.HasOne("Entities.Models.Post", "Post")
                        .WithMany("Feedbacks")
                        .HasForeignKey("PostId")
                        .HasConstraintName("FK_Feedback_Post");

                    b.HasOne("Entities.Models.PostOfContest", "PostOfCotest")
                        .WithMany("Feedbacks")
                        .HasForeignKey("PostOfContestId")
                        .HasConstraintName("FK_Feedback_PostOfContest");

                    b.HasOne("Entities.Models.Account", "Sender")
                        .WithMany("FeedbackSenders")
                        .HasForeignKey("SenderId")
                        .HasConstraintName("FK_Feedback_Account1");

                    b.HasOne("Entities.Models.TradingPost", "TradingPost")
                        .WithMany("Feedbacks")
                        .HasForeignKey("TradingPostId")
                        .HasConstraintName("FK_Feedback_TradingPost");

                    b.Navigation("Account");

                    b.Navigation("AccountReply");

                    b.Navigation("Post");

                    b.Navigation("PostOfCotest");

                    b.Navigation("Sender");

                    b.Navigation("TradingPost");
                });

            modelBuilder.Entity("Entities.Models.FollowAccount", b =>
                {
                    b.HasOne("Entities.Models.Account", "AccountFollow")
                        .WithMany("FollowAccountAccountFollows")
                        .HasForeignKey("AccountFollowId")
                        .HasConstraintName("FK_FollowAccount_Account1")
                        .IsRequired();

                    b.HasOne("Entities.Models.Account", "Account")
                        .WithMany("FollowAccountAccounts")
                        .HasForeignKey("AccountId")
                        .HasConstraintName("FK_FollowAccount_Account")
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("AccountFollow");
                });

            modelBuilder.Entity("Entities.Models.FollowGroup", b =>
                {
                    b.HasOne("Entities.Models.Account", "Account")
                        .WithMany("FollowGroups")
                        .HasForeignKey("AccountId")
                        .HasConstraintName("FK_FollowGroup_Account")
                        .IsRequired();

                    b.HasOne("Entities.Models.Group", "Group")
                        .WithMany("FollowGroups")
                        .HasForeignKey("GroupId")
                        .HasConstraintName("FK_FollowGroup_Group")
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("Group");
                });

            modelBuilder.Entity("Entities.Models.Image", b =>
                {
                    b.HasOne("Entities.Models.Bill", "Bill")
                        .WithMany("Images")
                        .HasForeignKey("BillId")
                        .HasConstraintName("FK_Image_Bill");

                    b.HasOne("Entities.Models.Post", "Post")
                        .WithMany("Images")
                        .HasForeignKey("PostId")
                        .HasConstraintName("FK_Image_Post");

                    b.HasOne("Entities.Models.PostOfContest", "PostOfContest")
                        .WithMany("Images")
                        .HasForeignKey("PostOfContestId");

                    b.HasOne("Entities.Models.Prize", "Prize")
                        .WithMany("Images")
                        .HasForeignKey("PrizeId")
                        .HasConstraintName("FK_Image_Prize");

                    b.HasOne("Entities.Models.Toy", "Toy")
                        .WithMany("Images")
                        .HasForeignKey("ToyId")
                        .HasConstraintName("FK_Image_Toy");

                    b.HasOne("Entities.Models.TradingPost", "TradingPost")
                        .WithMany("Images")
                        .HasForeignKey("TradingPostId")
                        .HasConstraintName("FK_Image_TradingPost");

                    b.Navigation("Bill");

                    b.Navigation("Post");

                    b.Navigation("PostOfContest");

                    b.Navigation("Prize");

                    b.Navigation("Toy");

                    b.Navigation("TradingPost");
                });

            modelBuilder.Entity("Entities.Models.JoinedToContest", b =>
                {
                    b.HasOne("Entities.Models.Account", "Account")
                        .WithMany("ContestJoined")
                        .HasForeignKey("AccountId")
                        .HasConstraintName("FK_Account_JoinedContest")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entities.Models.Contest", "Contest")
                        .WithMany("AccountJoined")
                        .HasForeignKey("ContestId")
                        .HasConstraintName("FK_Contest_JoinedAccount")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("Contest");
                });

            modelBuilder.Entity("Entities.Models.ManageGroup", b =>
                {
                    b.HasOne("Entities.Models.Account", "Account")
                        .WithMany("ManageGroups")
                        .HasForeignKey("AccountId")
                        .HasConstraintName("FK_ManageGroup_Account")
                        .IsRequired();

                    b.HasOne("Entities.Models.Group", "Group")
                        .WithMany("ManageGroups")
                        .HasForeignKey("GroupId")
                        .HasConstraintName("FK_ManageGroup_Group")
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("Group");
                });

            modelBuilder.Entity("Entities.Models.Notification", b =>
                {
                    b.HasOne("Entities.Models.Account", "Account")
                        .WithMany("Notifications")
                        .HasForeignKey("AccountId")
                        .HasConstraintName("FK_Notification_Account");

                    b.HasOne("Entities.Models.Contest", "Contest")
                        .WithMany("Notifications")
                        .HasForeignKey("ContestId")
                        .HasConstraintName("FK_Notification_Contest");

                    b.HasOne("Entities.Models.Post", "Post")
                        .WithMany("Notifications")
                        .HasForeignKey("PostId")
                        .HasConstraintName("FK_Notification_Post");

                    b.HasOne("Entities.Models.PostOfContest", "PostOfContest")
                        .WithMany("Notifications")
                        .HasForeignKey("PostOfContestId");

                    b.HasOne("Entities.Models.TradingPost", "TradingPost")
                        .WithMany("Notifications")
                        .HasForeignKey("TradingPostId")
                        .HasConstraintName("FK_Notification_TradingPost");

                    b.Navigation("Account");

                    b.Navigation("Contest");

                    b.Navigation("Post");

                    b.Navigation("PostOfContest");

                    b.Navigation("TradingPost");
                });

            modelBuilder.Entity("Entities.Models.Post", b =>
                {
                    b.HasOne("Entities.Models.Account", "Account")
                        .WithMany("Posts")
                        .HasForeignKey("AccountId")
                        .HasConstraintName("FK_Post_Account");

                    b.HasOne("Entities.Models.Group", "Group")
                        .WithMany("Posts")
                        .HasForeignKey("GroupId")
                        .HasConstraintName("FK_Post_Group");

                    b.HasOne("Entities.Models.Toy", "Toy")
                        .WithMany("Posts")
                        .HasForeignKey("ToyId")
                        .HasConstraintName("FK_Post_Toy");

                    b.Navigation("Account");

                    b.Navigation("Group");

                    b.Navigation("Toy");
                });

            modelBuilder.Entity("Entities.Models.PostOfContest", b =>
                {
                    b.HasOne("Entities.Models.Account", "Account")
                        .WithMany("PostOfContests")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entities.Models.Contest", "Contest")
                        .WithMany("Posts")
                        .HasForeignKey("ContestId")
                        .HasConstraintName("FK_PostOfContest_Contest")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("Contest");
                });

            modelBuilder.Entity("Entities.Models.PrizeContest", b =>
                {
                    b.HasOne("Entities.Models.Contest", "Contest")
                        .WithMany("PrizeContests")
                        .HasForeignKey("ContestId")
                        .HasConstraintName("FK_Prize_Contest_Contest")
                        .IsRequired();

                    b.HasOne("Entities.Models.Prize", "Prize")
                        .WithMany("PrizeContests")
                        .HasForeignKey("PrizeId")
                        .HasConstraintName("FK_Prize_Contest_Prize")
                        .IsRequired();

                    b.Navigation("Contest");

                    b.Navigation("Prize");
                });

            modelBuilder.Entity("Entities.Models.Rate", b =>
                {
                    b.HasOne("Entities.Models.Account", "Account")
                        .WithMany("Rates")
                        .HasForeignKey("AccountId")
                        .HasConstraintName("FK_RateContest_Account");

                    b.HasOne("Entities.Models.PostOfContest", "PostOfContest")
                        .WithMany("Rates")
                        .HasForeignKey("PostOfContestId")
                        .HasConstraintName("FK_Rate_PostOfContest")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("PostOfContest");
                });

            modelBuilder.Entity("Entities.Models.RateSeller", b =>
                {
                    b.HasOne("Entities.Models.Account", "Buyer")
                        .WithMany("RateSellersBuyer")
                        .HasForeignKey("BuyerId")
                        .HasConstraintName("FK_RateSeller_Account_Buyer")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entities.Models.Account", "Seller")
                        .WithMany("RateSellersSeller")
                        .HasForeignKey("SellerId")
                        .HasConstraintName("FK_RateSeller_Account_Seller")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Buyer");

                    b.Navigation("Seller");
                });

            modelBuilder.Entity("Entities.Models.ReactComment", b =>
                {
                    b.HasOne("Entities.Models.Account", "Account")
                        .WithMany("ReactComments")
                        .HasForeignKey("AccountId")
                        .HasConstraintName("FK__ReactComm__Accou__339FAB6E")
                        .IsRequired();

                    b.HasOne("Entities.Models.Comment", "Comment")
                        .WithMany("ReactComments")
                        .HasForeignKey("CommentId")
                        .HasConstraintName("FK__ReactComm__Comme__3493CFA7")
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("Comment");
                });

            modelBuilder.Entity("Entities.Models.ReactPost", b =>
                {
                    b.HasOne("Entities.Models.Account", "Account")
                        .WithMany("ReactPosts")
                        .HasForeignKey("AccountId")
                        .HasConstraintName("FK_ReactPost_Account")
                        .IsRequired();

                    b.HasOne("Entities.Models.Post", "Post")
                        .WithMany("ReactPosts")
                        .HasForeignKey("PostId")
                        .HasConstraintName("FK_ReactPost_Post")
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("Post");
                });

            modelBuilder.Entity("Entities.Models.ReactTradingPost", b =>
                {
                    b.HasOne("Entities.Models.Account", "Account")
                        .WithMany("ReactTradingPosts")
                        .HasForeignKey("AccountId")
                        .HasConstraintName("FK_ReactTradingPost_Account")
                        .IsRequired();

                    b.HasOne("Entities.Models.TradingPost", "TradingPost")
                        .WithMany("ReactTradingPosts")
                        .HasForeignKey("TradingPostId")
                        .HasConstraintName("FK_ReactTradingPost_TradingPost")
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("TradingPost");
                });

            modelBuilder.Entity("Entities.Models.Reward", b =>
                {
                    b.HasOne("Entities.Models.Account", "Account")
                        .WithMany("Rewards")
                        .HasForeignKey("AccountId")
                        .HasConstraintName("FK_Reward_Account")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entities.Models.Contest", "Contest")
                        .WithMany("Rewards")
                        .HasForeignKey("ContestId")
                        .HasConstraintName("FK_Reward_Contest")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entities.Models.PostOfContest", "PostOfContest")
                        .WithMany()
                        .HasForeignKey("PostOfContestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entities.Models.Prize", "Prize")
                        .WithMany("Rewards")
                        .HasForeignKey("PrizeId")
                        .HasConstraintName("FK_Reward_Prize")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("Contest");

                    b.Navigation("PostOfContest");

                    b.Navigation("Prize");
                });

            modelBuilder.Entity("Entities.Models.Toy", b =>
                {
                    b.HasOne("Entities.Models.Brand", "Brand")
                        .WithMany("Toys")
                        .HasForeignKey("BrandId")
                        .HasConstraintName("FK_Toy_Brand");

                    b.HasOne("Entities.Models.Type", "Type")
                        .WithMany("Toys")
                        .HasForeignKey("TypeId")
                        .HasConstraintName("FK_Toy_Type");

                    b.Navigation("Brand");

                    b.Navigation("Type");
                });

            modelBuilder.Entity("Entities.Models.TradingPost", b =>
                {
                    b.HasOne("Entities.Models.Account", "Account")
                        .WithMany("TradingPosts")
                        .HasForeignKey("AccountId")
                        .HasConstraintName("FK_TradingPost_Account");

                    b.HasOne("Entities.Models.Brand", "Brand")
                        .WithMany("TradingPosts")
                        .HasForeignKey("BrandId");

                    b.HasOne("Entities.Models.Group", "Group")
                        .WithMany("TradingPosts")
                        .HasForeignKey("GroupId")
                        .HasConstraintName("FK_TradingPost_Group")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entities.Models.Toy", "Toy")
                        .WithMany("TradingPosts")
                        .HasForeignKey("ToyId")
                        .HasConstraintName("FK_TradingPost_Toy");

                    b.HasOne("Entities.Models.Type", "Type")
                        .WithMany("TradingPosts")
                        .HasForeignKey("TypeId");

                    b.Navigation("Account");

                    b.Navigation("Brand");

                    b.Navigation("Group");

                    b.Navigation("Toy");

                    b.Navigation("Type");
                });

            modelBuilder.Entity("Entities.Models.Account", b =>
                {
                    b.Navigation("BillsBuyer");

                    b.Navigation("BillsSeler");

                    b.Navigation("Chats");

                    b.Navigation("Comments");

                    b.Navigation("ContestJoined");

                    b.Navigation("Evaluates");

                    b.Navigation("FavoriteBrands");

                    b.Navigation("FavoriteTypes");

                    b.Navigation("FeedbackAccountReplies");

                    b.Navigation("FeedbackAccounts");

                    b.Navigation("FeedbackSenders");

                    b.Navigation("FollowAccountAccountFollows");

                    b.Navigation("FollowAccountAccounts");

                    b.Navigation("FollowGroups");

                    b.Navigation("ManageGroups");

                    b.Navigation("Notifications");

                    b.Navigation("PostOfContests");

                    b.Navigation("Posts");

                    b.Navigation("Rates");

                    b.Navigation("RateSellersBuyer");

                    b.Navigation("RateSellersSeller");

                    b.Navigation("ReactComments");

                    b.Navigation("ReactPosts");

                    b.Navigation("ReactTradingPosts");

                    b.Navigation("Rewards");

                    b.Navigation("TradingPosts");
                });

            modelBuilder.Entity("Entities.Models.Bill", b =>
                {
                    b.Navigation("Images");
                });

            modelBuilder.Entity("Entities.Models.Brand", b =>
                {
                    b.Navigation("Contests");

                    b.Navigation("FavoriteBrands");

                    b.Navigation("Toys");

                    b.Navigation("TradingPosts");
                });

            modelBuilder.Entity("Entities.Models.Comment", b =>
                {
                    b.Navigation("ReactComments");
                });

            modelBuilder.Entity("Entities.Models.Contest", b =>
                {
                    b.Navigation("AccountJoined");

                    b.Navigation("Evaluates");

                    b.Navigation("Notifications");

                    b.Navigation("Posts");

                    b.Navigation("PrizeContests");

                    b.Navigation("Rewards");
                });

            modelBuilder.Entity("Entities.Models.Group", b =>
                {
                    b.Navigation("FollowGroups");

                    b.Navigation("ManageGroups");

                    b.Navigation("Posts");

                    b.Navigation("TradingPosts");
                });

            modelBuilder.Entity("Entities.Models.Post", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("Feedbacks");

                    b.Navigation("Images");

                    b.Navigation("Notifications");

                    b.Navigation("ReactPosts");
                });

            modelBuilder.Entity("Entities.Models.PostOfContest", b =>
                {
                    b.Navigation("Feedbacks");

                    b.Navigation("Images");

                    b.Navigation("Notifications");

                    b.Navigation("Rates");
                });

            modelBuilder.Entity("Entities.Models.Prize", b =>
                {
                    b.Navigation("Images");

                    b.Navigation("PrizeContests");

                    b.Navigation("Rewards");
                });

            modelBuilder.Entity("Entities.Models.Toy", b =>
                {
                    b.Navigation("Images");

                    b.Navigation("Posts");

                    b.Navigation("TradingPosts");
                });

            modelBuilder.Entity("Entities.Models.TradingPost", b =>
                {
                    b.Navigation("Bills");

                    b.Navigation("Comments");

                    b.Navigation("Feedbacks");

                    b.Navigation("Images");

                    b.Navigation("Notifications");

                    b.Navigation("ReactTradingPosts");
                });

            modelBuilder.Entity("Entities.Models.Type", b =>
                {
                    b.Navigation("Contests");

                    b.Navigation("FavoriteTypes");

                    b.Navigation("Toys");

                    b.Navigation("TradingPosts");
                });
#pragma warning restore 612, 618
        }
    }
}
